Repository mirest/ah-haven-space-sprinters, pull requests merged in 2019-03, with the labels that each got.

#12 #164694215 Receive jwt token on successfull registration
  .gitignore
  authors/apps/authentication/backends.py
  authors/apps/authentication/models.py
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/test_base.py
  authors/apps/authentication/tests/test_views.py
  authors/apps/authentication/urls.py
  authors/apps/authentication/views.py
  config/settings/default.py
Labels: Done, review required, still working

#13 #164694216 Add descriptive messages on user login/registration
  authors/apps/authentication/models.py
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/test_base.py
  authors/apps/authentication/tests/test_validations.py
  authors/apps/authentication/tests/test_views.py
Labels: Done, enhancement, review required

#15 #164694217 Users should receive an email notification on successful signup
  app.json
  authors/apps/authentication/backends.py
  authors/apps/authentication/migrations/0002_user_is_valid.py
  authors/apps/authentication/models.py
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/test_views.py
  authors/apps/authentication/urls.py
  authors/apps/authentication/views.py
  config/settings/default.py
  requirements.txt
Labels: review required, still working

#14 #164694218 Users should be able to reset password via email
  authors/apps/authentication/backends.py
  authors/apps/authentication/models.py
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/test_base.py
  authors/apps/authentication/tests/test_user.py
  authors/apps/authentication/tests/test_validations.py
  authors/apps/authentication/tests/test_views.py
  authors/apps/authentication/tokens.py
  authors/apps/authentication/urls.py
  authors/apps/authentication/views.py
  config/settings/default.py
Labels: Done, review required, still working
