Repository mirest/ah-haven-space-sprinters, pull requests merged in 2019-04, with the labels that each got.

#19 #164694220 Create user profiles upon registration
  README.md
  app.json
  authors/apps/authentication/default_renderer.py
  authors/apps/authentication/migrations/0001_initial.py
  authors/apps/authentication/migrations/0002_user_is_valid.py
  authors/apps/authentication/models.py
  authors/apps/authentication/renderers.py
  authors/apps/authentication/tests/test_base.py
  authors/apps/authentication/tests/test_views.py
  authors/apps/authentication/views.py
  authors/apps/profiles/admin.py
  authors/apps/profiles/apps.py
  authors/apps/profiles/migrations/0001_initial.py
  authors/apps/profiles/migrations/0002_auto_20190331_2316.py
  authors/apps/profiles/migrations/0003_auto_20190331_2336.py
  authors/apps/profiles/migrations/__init__.py
  authors/apps/profiles/models.py
  authors/apps/profiles/renderers.py
  authors/apps/profiles/serializers.py
  authors/apps/profiles/tests.py
  authors/apps/profiles/urls.py
  authors/apps/profiles/views.py
  authors/apps/utilities/__init__.py
  authors/apps/utilities/custom_permissions/__init__.py
  authors/apps/utilities/custom_permissions/permissions.py
  authors/apps/utilities/messages.py
  authors/apps/utilities/tests/__init__.py
  authors/apps/utilities/tests/test_validation_helpers.py
  authors/apps/utilities/validators/__init__.py
  authors/apps/utilities/validators/validation_helpers.py
  config/urls.py
  requirements.txt
Labels: still working

#21 #1650880191 Enhance api structure and api documentation.
  README.md
  authors/apps/authentication/admin.py
  authors/apps/authentication/tests/test_base.py
  authors/apps/authentication/tests/test_validations.py
  authors/apps/authentication/tests/test_views.py
  authors/apps/authentication/views.py
  config/urls.py
Labels: still working

#18 #164694221 Biuld out Rest endpoints for articles
  authors/apps/articles/__init__.py
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/migrations/0002_auto_20190405_0339.py
  authors/apps/articles/migrations/__init__.py
  authors/apps/articles/models.py
  authors/apps/articles/renderers.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/__init__.py
  authors/apps/articles/tests/test_base.py
  authors/apps/articles/tests/test_user.py
  authors/apps/articles/tests/test_validations.py
  authors/apps/articles/tests/test_views.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  config/settings/default.py
  config/urls.py
Labels: review required, still working

#22 #164694231 List user functionality
  authors/apps/articles/renderers.py
  authors/apps/authentication/default_renderer.py
  authors/apps/authentication/migrations/0001_initial.py
  authors/apps/authentication/models.py
  authors/apps/authentication/renderers.py
  authors/apps/authentication/serializers.py
  authors/apps/authentication/urls.py
  authors/apps/authentication/views.py
  authors/apps/core/exceptions.py
  authors/apps/profiles/migrations/0001_initial.py
  authors/apps/profiles/models.py
  authors/apps/profiles/renderers.py
  authors/apps/profiles/serializers.py
  authors/apps/profiles/tests.py
  authors/apps/profiles/urls.py
  authors/apps/profiles/views.py
  authors/apps/utilities/validators/validation_helpers.py
Labels: review required, still working

#26 #164694233 Add pagination support to articles
  authors/apps/articles/pagination.py
  authors/apps/articles/views.py
Labels: Done, review required

#23 #164694224 Users should comment on articles
  authors/apps/articles/serializers.py
  authors/apps/comments/__init__.py
  authors/apps/comments/migrations/0001_initial.py
  authors/apps/comments/migrations/__init__.py
  authors/apps/comments/models.py
  authors/apps/comments/renderers.py
  authors/apps/comments/serializers.py
  authors/apps/comments/tests/__init__.py
  authors/apps/comments/tests/test_base.py
  authors/apps/comments/tests/test_views.py
  authors/apps/comments/urls.py
  authors/apps/comments/views.py
  config/settings/default.py
  config/urls.py
Labels: Done, review required

#25 #164694236 User should be able to see how long it takes to read an article
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_base.py
  authors/apps/articles/tests/test_models.py
  authors/apps/articles/tests/test_views.py
  authors/apps/articles/views.py
  authors/apps/utilities/estimators.py
Labels: Done, review required

#27 #164694237 Share Articles across different channels
  authors/apps/articles/renderers.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_base.py
  authors/apps/articles/tests/test_views.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
Labels: Done, review required

#24 #164694227 Users should be able to follow each other
  .travis.yml
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_base.py
  authors/apps/articles/tests/test_views.py
  authors/apps/authentication/backends.py
  authors/apps/authentication/default_renderer.py
  authors/apps/authentication/migrations/0002_user_is_valid.py
  authors/apps/authentication/renderers.py
  authors/apps/authentication/serializers.py
  authors/apps/authentication/tests/test_base.py
  authors/apps/authentication/tests/test_user.py
  authors/apps/authentication/tests/test_validations.py
  authors/apps/authentication/tests/test_views.py
  authors/apps/authentication/tokens.py
  authors/apps/authentication/urls.py
  authors/apps/authentication/views.py
  authors/apps/profiles/migrations/0004_follower.py
  authors/apps/profiles/models.py
  authors/apps/profiles/renderers.py
  authors/apps/profiles/serializers.py
  authors/apps/profiles/tests.py
  authors/apps/profiles/urls.py
  authors/apps/profiles/views.py
  config/settings/default.py
  config/settings/development.py
  config/settings/production.py
  config/settings/staging.py
  config/settings/testing.py
  config/urls.py
  config/wsgi.py
  manage.py
Labels: Done, enhancement, review required

#31 #164694240 Authors can comment on text within article
  authors/apps/comments/migrations/0002_comment_comment_on_text.py
  authors/apps/comments/migrations/0003_auto_20190417_1643.py
  authors/apps/comments/models.py
  authors/apps/comments/serializers.py
  authors/apps/comments/tests/test_base.py
  authors/apps/comments/tests/test_views.py
  authors/apps/comments/views.py
Labels: Done, review required

#30 #164694222 users able rate article
  authors/apps/articles/migrations/0001_initial.py
  authors/apps/articles/migrations/0004_auto_20190416_1306.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_base.py
  authors/apps/articles/tests/test_views.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
  authors/apps/authentication/admin.py
  authors/apps/authentication/tests/test_base.py
  authors/apps/authentication/tests/test_views.py
  authors/apps/comments/migrations/0001_initial.py
  authors/apps/profiles/renderers.py
  authors/apps/profiles/serializers.py
  authors/apps/profiles/views.py
  authors/apps/utilities/messages.py
  authors/apps/utilities/tests/test_validation_helpers.py
Labels: Done, enhancement, review required

#28 #164694226 Implement like or dislike an article functionality
  authors/apps/articles/like_views.py
  authors/apps/articles/migrations/0005_articlelikes.py
  authors/apps/articles/models.py
  authors/apps/articles/renderers.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_base.py
  authors/apps/articles/tests/test_views.py
  authors/apps/articles/urls.py
  authors/apps/articles/utilities.py
  authors/apps/profiles/tests.py
  requirements.txt
Labels: Done, review required

#33 #164694242 Like or unlike a comment
  authors/apps/articles/serializers.py
  authors/apps/comments/migrations/0004_commentlike.py
  authors/apps/comments/models.py
  authors/apps/comments/serializers.py
  authors/apps/comments/tests/test_views.py
  authors/apps/comments/urls.py
  authors/apps/comments/views.py
Labels: still working

#34 #164694239 Users can report an article
  authors/apps/articles/migrations/0006_reportarticle.py
  authors/apps/articles/migrations/0007_auto_20190425_0715.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_base.py
  authors/apps/articles/tests/test_views.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
Labels: Done, review required

#35 #164694238 Users should be able to bookmark articles
  authors/apps/articles/migrations/0008_auto_20190425_1325.py
  authors/apps/articles/models.py
  authors/apps/articles/serializers.py
  authors/apps/articles/tests/test_views.py
  authors/apps/articles/urls.py
  authors/apps/articles/views.py
Labels: Done, enhancement, review required
